### ISSUE TITLE
ios端的a-shell安装epubhv遇到的fugashi问题，请教下。

### ISSUE THREAD

**Issue by fqw000** [yihong0618/epubhv#10]
- a—shell mini
- Python 3.11.0
- pip 23.3.2
  
安装epubhv成功，运行却一直报错fugashi重装也没起作用，请指教。

[Documents]$ pip install epubhv
Defaulting to user installation because normal site-
packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.c
n/simple
Requirement already satisfied: epubhv in /var/mobile
/Containers/Data/Application/A3D6ABA5-6EFD-4792-9707
-EA0AE3678F47/Library/lib/python3.11/site-packages (
0.4.1)
Requirement already satisfied: beautifulsoup4==4.12.
2 in /var/mobile/Containers/Data/Application/A3D6ABA
5-6EFD-4792-9707-EA0AE3678F47/Library/lib/python3.11
/site-packages (from epubhv) (4.12.2)
Requirement already satisfied: cssutils==2.7.1 in /v
ar/mobile/Containers/Data/Application/A3D6ABA5-6EFD-
4792-9707-EA0AE3678F47/Library/lib/python3.11/site-p
ackages (from epubhv) (2.7.1)
Requirement already satisfied: lxml==4.9.3 in /priva
te/var/containers/Bundle/Application/C53C589E-EB81-4
638-9DF5-5656C96958CF/a-Shell-mini.app/Library/lib/p
ython3.11/site-packages (from epubhv) (4.9.3)
Requirement already satisfied: opencc-python-reimple
mented==0.1.7 in /var/mobile/Containers/Data/Applica
tion/A3D6ABA5-6EFD-4792-9707-EA0AE3678F47/Library/li
b/python3.11/site-packages (from epubhv) (0.1.7)
Requirement already satisfied: soupsieve==2.5 in /va
r/mobile/Containers/Data/Application/A3D6ABA5-6EFD-4
792-9707-EA0AE3678F47/Library/lib/python3.11/site-packages (from typed-argument-parser==1.8.1->e
pubhv) (0.15)
Requirement already satisfied: mypy-extensions>=0.3.0 in /var/mobile/Containers/Data/Application/A3D6ABA5-6EFD-4792-9707-EA0AE3678F47/Library/lib/python3.11/site-packages (from typing-inspect>=0.7.1->typed-argument-parser==1.8.1->epubhv) (1.0.0)
Requirement already satisfied: typing-extensions>=3.7.4 in /private/var/containers/Bundle/Application/C53C589E-EB81-4638-9DF5-5656C96958CF/a-Shell-mini.app/Library/lib/python3.11/site-packages (from typing-inspect>=0.7.1->typed-argument-parser==1.8.1->epubhv) (4.8.0)

[Documents]$ pip show epubhv
Name: epubhv
Version: 0.4.1
Summary: make your epub books vertical or horizontal.
Home-page: 
Author: 
Author-email: yihong0618 <zouzou0208@gmail.com>
License: MIT
Location: /var/mobile/Containers/Data/Application/A3D6ABA5-6EFD-4792-9707-EA0AE3678F47/Library/lib/python3.11/site-packages
Requires: beautifulsoup4, cssutils, fugashi, jieba, lxml, opencc-python-reimplemented, pypinyin, soupsieve, typed-argument-parser, unidic_lite
Required-by: 

[Documents]$ epubhv 浮木.epub --h --ruby 
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/A3D6ABA5-6EFD-4792-9707-EA0AE3678F47/Library/bin/epubhv", line 5, in <module>
    from epubhv.cli import main
  File "/var/mobile/Containers/Data/Application/A3D6ABA5-6EFD-4792-9707-EA0AE3678F47/Library/lib/python3.11/site-packages/epubhv/cli.py", line 5, in <module>
    from epubhv.epubhv import EPUBHV, list_all_epub_in_dir
  File "/var/mobile/Containers/Data/Application/A3D6ABA5-6EFD-4792-9707-EA0AE3678F47/Library/lib/python3.11/site-packages/epubhv/epubhv.py", line 20, in <module>
    from epubhv.yomituki import RubySoup, string_con
tainers
  File "/var/mobile/Containers/Data/Application/A3D6
ABA5-6EFD-4792-9707-EA0AE3678F47/Library/lib/python3
.11/site-packages/epubhv/yomituki.py", line 14, in <
module>
    from fugashi import Tagger
  File "/var/mobile/Containers/Data/Application/A3D6
ABA5-6EFD-4792-9707-EA0AE3678F47/Library/lib/python3
.11/site-packages/fugashi/__init__.py", line 1, in <
module>
    from .fugashi import *
ImportError: dlopen(/private/var/containers/Bundle/A
pplication/C53C589E-EB81-4638-9DF5-5656C96958CF/a-Sh
ell-mini.app/Frameworks/python3_ios-fugashi.fugashi.
framework/python3_ios-fugashi.fugashi, 0x0002): trie
d: '/private/var/containers/Bundle/Application/C53C5
89E-EB81-4638-9DF5-5656C96958CF/a-Shell-mini.app/Fra
meworks/python3_ios-fugashi.fugashi.framework/python
3_ios-fugashi.fugashi' (errno=2), '/private/preboot/
Cryptexes/OS/private/var/containers/Bundle/Applicati
on/C53C589E-EB81-4638-9DF5-5656C96958CF/a-Shell-mini
.app/Frameworks/python3_ios-fugashi.fugashi.framewor
k/python3_ios-fugashi.fugashi' (errno=2), '/private/
var/containers/Bundle/Application/C53C589E-EB81-4638
-9DF5-5656C96958CF/a-Shell-mini.app/Frameworks/pytho
n3_ios-fugashi.fugashi.framework/python3_ios-fugashi
.fugashi' (errno=2)

**Comment by yihong0618** [comment]
不太知道 ios 下的行为我们研究下
大概率是 fugashi 依赖 Mecab 而 mecab 无法在 iOS 上运行

**Comment by fqw000** [comment]
产品很棒，感谢大佬付出！
