### ISSUE TITLE
使用「粤语注音」时，错误的进行了两次注音

### ISSUE THREAD

**Issue by Daniel-2048** [yihong0618/epubhv#11]
在 macOS 14 中使用新增的「粤语注音」时，epubhv 会错误的在括号中进行两次注音（如图高亮部分所示），在全文注音中均出现了此现象。pip 版本为 23.3.1，Python 版本为 3.11。
<img width="1136" alt="image" src="https://github.com/yihong0618/epubhv/assets/85775654/0dff538f-ba1a-4b3f-8f4c-7a69bb2676cd">
**所使用的 epub 和注音结果下附于 zip 中**
[Archive.zip](https://github.com/yihong0618/epubhv/files/13809879/Archive.zip)

**Comment by yihong0618** [comment]
@Daniel-2048 应该修复了

pip install -U epubhv
