### ISSUE TITLE
Thoughts on smaller methods, and more on extensibility

### ISSUE THREAD

**Issue by jt-wang** [yihong0618/epubhv#9]
Hi @yihong0618, thanks for building this great project! As I have touched more on it, I came up with some thoughts to share with you.

## Separate the methods
Currently, the project is relatively short - only several hundreds of code. However, there is still space of improvement, especially in further separate the methods into smaller ones or into their own modules. e.g. 

**utility:**
1. File system management utils (create temp & remove temp directories and files)
2. File processing utils (dealing with anything with creating  intermediate helper files to be processed by bs4 or cssutils)
3. HTML processing utils (mainly bs4 relevant) 
4. CSS processing utils (cssutils-relevant)

and

**pluggable functionality module:**
1. direction-changing module
3.  openCC convert module
4. punctuation convert module

and 

**User Interface**:
It can be totally decoupled from `utility` and `pluggable functionality module:`,
e.g. 
1. CLI that contains both args parsing and CLI output
2. Since it's already decoupled, it can unblock EPUBHV's potentials to be integrated into various services. e.g. can be exposed to https://github.com/yihong0618/bilingual_book_maker as an optional module too.

Let me how you think about it :)

**Comment by yihong0618** [comment]
of course strongly agree with you just go for it.
to be honest, [bilingual_book_maker](https://github.com/yihong0618/bilingual_book_maker) is kind of out of control because of we messed up the code, and I lost interest to add more feature on it, so just do it, and really thanks~

**Comment by jt-wang** [comment]
@yihong0618 Thanks! I will do when I got more time later (I've been totally packed this week). Meanwhile, it would be great if other contributors are interested in this refactoring.

**Comment by yihong0618** [comment]
OK, I pin this issue
